### ISSUE TITLE
Generate 1/f component

### ISSUE THREAD

**Issue by huhell** [pcubillos/mc3#115]
Hello,
I am trying to generate pure 1/f component as described in your paper: random numbers to produce wavelet coefficients respecting the variances given by equations (10) and (11). I quite struggle to actually get it right. The piece of code I have is so far (which does not quite reproduce your figure 2) is:

import dwt as dwt
def create_rednoise(n, sigma_r, sigma_w):
        """
        create correlated noise component
        """
        M = np.int(np.ceil(np.log(n) / np.log(2)))
        if 2**M != n:
                print "size is not a power of 2"

        gamma = 1
        gg = 1/(2*np.log(2))

        wv = np.zeros((n))

        sm2 = sigma_r**2 * 2**(-gamma) * gg + sigma_w**2
        wv[0] = np.random.normal(0, np.sqrt(sm2))

        k = 1
        for i in np.arange(1,M+1):
                sm2 = sigma_r**2 * 2**(np.int(-gamma*i)) + sigma_w**2
                for m in np.arange(0,2**(i-1)):
                        wv[k] = np.random.normal(0, np.sqrt(sm2))
                        k += 1

        redcomp = dwt.daubechies4(wv, -1)
        return redcomp

rednoise = create_rednoise(1024, 1.6e-3/3, 1.6e-3).

Thanks for your help !
Hugo.

**Comment by pcubillos** [comment]
Hi Hugo,
Took me some time, but I managed to find the script I used to create that plot.  I updated to the latest MC3 version (3.0.0) and added some comments to explain what I was doing (I also stripped out everything except how to make the noise components).  Here it is below, let me know whether this is what you were looking for or not.

```python
import numpy as np
import matplotlib.pyplot as plt

# Make sure you have already installed MC3 (pip install mc3)
import mc3.stats as ms
import mc3.utils as mu

# Phase parameter:
ndata = 1700
phasei, phasef = 0.39, 0.63
phase = np.linspace(phasei, phasef, ndata)
flux  = 2.5815e+04

# Noise:
gamma  = 1.0
g = 0.72
# Next larger number than size(phase) of shape 2**N, with N integer:
nrx = int(2**np.ceil(np.log2(ndata)))
m = np.ceil(np.log2(np.arange(1, nrx+1)))-1
m[0:2] = 1

# This is the strategy:
# Construct variance in wavelet space, then take inverse wavelet transform:

# Choose an arbitrary number for std-dev of white component:
sigmaw = 2.5e-03
# All white, zero red:
variance = np.zeros(nrx, np.double) +  sigmaw**2
white = np.random.normal(0, np.sqrt(variance))
white_noise = ms.dwt_daub4(white, inverse=True)[0:ndata]

# Given sigmaw above, find sigmar (by trial and error) such that
# the variances of white an red noise have these ratios:
#     For std(red)/std(white) = 0.25, set: sigmar = 0.89e-02
#     For std(red)/std(white) = 0.50, set: sigmar = 1.78e-02

# All red, zero white:
red_noise = []
for sigmar in [0.89e-02, 1.78e-02]:
    sigmaw = 0.0
    variance      = sigmar**2 * 2**(-gamma*m) + sigmaw**2
    variance[0:2] = sigmar**2 * 2**(-gamma)*g + sigmaw**2
    red = np.random.normal(0, np.sqrt(variance))
    red_noise.append(ms.dwt_daub4(red, inverse=True)[0:ndata])

# Check that std ratios are approximately OK:
for red in red_noise:
    print(f'std(red)/std(white) = {np.std(red)/np.std(white_noise):.2f}')

plt.figure(2)
plt.clf()
plt.subplot(211)
plt.plot(phase, flux*white_noise,  ".", c="0.6", ms=5, label="uncorrelated")
plt.plot(phase, flux*red_noise[0], ".", c="k",   ms=5, label="correlated")
plt.xlim(phase[0]-0.005, phase[-1]+0.005)
plt.xticks(visible=False)
plt.ylim(-220, 310)
plt.ylabel("Flux", fontsize=14)
plt.legend(loc="upper left")

plt.subplot(212)
plt.plot(phase, flux*white_noise,  ".", c="0.6", ms=5, label="uncorrelated")
plt.plot(phase, flux*red_noise[1], ".", c="k",   ms=5, label="correlated")
plt.xlim(phase[0]-0.005, phase[-1]+0.005)
plt.ylim(-220, 310)
plt.ylabel("Flux", fontsize=14)
plt.xlabel("Orbital phase", fontsize=fs)
plt.tight_layout()
```

**Comment by huhell** [comment]
Hi Patricio,

That's fantastic, thanks a lot ! I'll check it out but somehow the rms of my red noise is incorrect. Could it be related to the fact that I use dwt.daubechies4() instead of ms.dwt_daub4() ?

Hugo.

**Comment by huhell** [comment]
Fount it. I was actually setting sigma_r = 0.5 * sigma_w, instead of setting std(red)/std(white) = 0.5. Thanks again for the quick and useful help !

Best,
Hugo.

**Comment by pcubillos** [comment]
OK, cool!
