### ISSUE TITLE
Typo wavelet-based chisq

### ISSUE THREAD

**Issue by huhell** [pcubillos/mc3#116]
Hi again Patricio,

I just updated to new version of mc3, very nice thanks !
I think there is a typo in the stats.dwt_chisq function. It should be:
```
iprior = (priorlow > 0) & (priorup > 0)
    dprior = (params - priors)[iprior]
    return dwt.chisq(params, model, data, dprior, priorlow**[iprior]**, priorup**[iprior]**)

```
(the **[iprior]** have been forgotten if I am correct). Otherwise the chisq returned is 'nan'.

Best,
Hugo.

**Comment by pcubillos** [comment]
Hi,
Yeah, that looks right. I'll take a better look and fix it.  Thanks for the heads up!

**Comment by pcubillos** [comment]
OK, it should work now in the latest version.
Thanks!

**Comment by huhell** [comment]
Great, thanks !
