### ISSUE TITLE
Segmentation fault Python3 dwt

### ISSUE THREAD

**Issue by huhell** [pcubillos/mc3#118]
Hi Patricio,

Thanks for the updated version, very nice !
I have switched to Python 3.6 and encounter a segmentation fault when using the `dwt_daub4` function in `stats.py` .
For instance:

```
import numpy as np
import mc3 as mc3

res = np.random.randn(64)*100e-6
dwt1 = mc3.stats.dwt_daub4(res,False)
```
Which returns, when running in debug with gdb (i.e. `gdb --args python3 script.py`):
```
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
daub4 (self=<optimized out>, args=<optimized out>) at src_c/_dwt.c:181
181	src_c/_dwt.c: No such file or directory
```

I need `dwt_daub4` to compute the time series of my correlated noise, after estimating sigma_r and sigma_w.

Thanks a lot !

**Comment by pcubillos** [comment]
Hi @huhell 
I'm sorry for this very late reply. You probably found another solution for what you needed... but anyways, I found the bug, there was a cpython piece of code that became obsolete. I updated the code and the routine is working now.
