### ISSUE TITLE
Issue with linking 'func' with some f2py generated module

### ISSUE THREAD

**Issue by akashgpt** [pcubillos/mc3#119]
Hi,

I apologize if this happens to be a trivial issue or due to some lack of understanding on my part. 

Nevertheless, an issue that I have found is that if you create a Fortran based library/module using f2py (which I have tested on python) and use it in defining 'func', MC3 doesn't work.

For instance, I created a Fortran based module for multiplication - say 'y=fort_mult(a,b)' (that gives y=a*b as its output).  I then used it with the example you have in your documentation where you define a func quad where you calculate 'y=p[0] + p[1]*x + p[2]*x**2', i.e. I replaced this defintion with 'y=fort_mult(p[0],1) + fort_mult(p[1],x) + fort_mult(p[2], x**2)'. But once I do this, MC3 stops working. Ofcourse, my actual Fortran code is much more involved but I also tested the code with the example I just explained.

Hope you can resolve this!

Thanks!

**Comment by pcubillos** [comment]
Hi Askash,

Are you setting ``func`` directly with the fortran function? Can you try wrapping your fortran function into a python function? Something like this:
```python
def py_mult(params, x):
    return fort_func(params, x)
```
And then set ``func=py_mult`` in the mc3 call.  It looks silly but it might be related to how Python internally handles the callable objets.  Let me know whether that works or not.

**Comment by akashgpt** [comment]
Hi Patricio,

Thanks for your reply.

No, I am not setting 'func' directly with the fortran function. f2py converts a fortran function into a '.so' library/module which can then be used as any other python function.

For instance, in reference to the example I give above:

I create a FORTRAN subroutine like (let's call the filename to be 'test_f.f90')
"
SUBROUTINE test(p_a, p_b, y)

    IMPLICIT NONE
    
    REAL, INTENT(IN) :: p_a, p_b
    REAL, INTENT(OUT) :: y

    y=p_a*p_b
        
END SUBROUTINE
"

Using f2py, I convert it to a python .so file (command: f2py3 -c test_f.f90 -m test_f). This then allows one to call this function in python by simply writing 

"
import test_f

print(test_f.__doc__)
print("2 x 7 =",test_f.test(2,7))
"

Output of the above code should be/is
"
This module 'test_f' is auto-generated with f2py (version:2).
Functions:
  y = test(p_a,p_b)
2 x 7 = 14
"

Now, as you can imagine, one could use this to function to replace  
"
y = p[0] + p[1]*x + p[2]*(x**2.0)
"
in your example in the documentation with
"
y=test_f.test(p[0],1) + test_f.test(p[1],x) + test_f.test(p[2],x**2.0)
" .

But this gives the error (in another case I simply get segmentation fault):
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
  Error in module: 'sampler_driver.py', function: 'sample', line: 349
    data must be an iterable or a file name.
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

Thanks,
Akash

**Comment by akashgpt** [comment]
Regarding my previous 'comment', some of the commands I mentioned didn't show up properly. I guess I should have used the 'insert code' option. So here are the three bits again that didn't show up correctly, just for completeness:
1.
`import test_f`
`print(test_f.__doc__)`
`print("2 x 7 =",test_f.test(2,7))`

2.
`y = p[0] + p[1]x + p[2](x**2.0)`

3.
`y=test_f.test(p[0],1) + test_f.test(p[1],x) + test_f.test(p[2],x**2.0)`

**Comment by pcubillos** [comment]
Aha, a couple things:

```
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
Error in module: 'sampler_driver.py', function: 'sample', line: 349
data must be an iterable or a file name.
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
```
This kind of error is pointing to the ``data`` input, rather than ``func``. So, check that you are passing an array correctly.

Now, that doesn't solve the issue with the segmentation faults.  Could you copy/paste your entire test script? (the python part where you combine your fortran .so routine into mc3).  Maybe I can see if there's something out of place.  If there's nothing obvious I'll play around with it to test (but at least I know that a colleague did use a fitting function that relied on an f2py-ed function, so there must be a way to get this working).

**Comment by akashgpt** [comment]
I am attaching a text file that has your mc3 code at the top (the example from documentation; the only modification here is in `func`). At the bottom of this file is a short Fortran code which you could save as 'test_f.f90' and convert it into a .so file with the command in the line preceding it (using f2py). I think if this does end up working, the segmentation fault issue might be due to some fault on my part or I can look into that later.

Thanks again.

[mc3_edited.txt](https://github.com/pcubillos/mc3/files/4583748/mc3_edited.txt)

**Comment by akashgpt** [comment]
I think I figured it out, at least the issue I raised here. Sorry for the trouble. It was a mistake on my part.

Thanks a lot for your time!

**Comment by akashgpt** [comment]
The issue was simply due to how I was passing arguments to the FORTRAN code. This issue did not have anything to do with your code. It was my fault. 

Thanks!

**Comment by pcubillos** [comment]
Oh, OK, no worries. Glad that you fixed it!
