### ISSUE TITLE
ModuleNotFoundError: No module named '_binarray'

### ISSUE THREAD

**Issue by klagyi** [pcubillos/mc3#122]
Hi,

I've just downloaded the code and I have a problem running it. It doesn't find the module '_binarray'. What is the problem?

Thanks,
Peter

>>> import mc3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/klagyi/astro/pythoncodes/mc3/mc3/__init__.py", line 4, in <module>
    from .sampler_driver import *
  File "/Users/klagyi/astro/pythoncodes/mc3/mc3/sampler_driver.py", line 21, in <module>
    from .fit_driver import fit
  File "/Users/klagyi/astro/pythoncodes/mc3/mc3/fit_driver.py", line 9, in <module>
    from . import stats as ms
  File "/Users/klagyi/astro/pythoncodes/mc3/mc3/stats/__init__.py", line 5, in <module>
    from .stats import *
  File "/Users/klagyi/astro/pythoncodes/mc3/mc3/stats/stats.py", line 26, in <module>
    import _binarray as ba
ModuleNotFoundError: No module named '_binarray'

**Comment by pcubillos** [comment]
Hi Peter,
It looks like you have not compiled the C-extension files of the code.  I'm guessing you cloned/downloaded the code rather than installed from pypi, right?

If so, you need to compile manually.  These commands should do it:
```shell
cd Users/klagyi/astro/pythoncodes/mc3/
python setup.py install
```
Let me know if this worked,
best.

**Comment by klagyi** [comment]
Hi Patricio,

Yes, I downloaded the code. I had some problems with pip...

I already installed it and I still have the error.

How can I install it another way?

Regards,
Peter

Patricio Cubillos <notifications@github.com> ezt írta (időpont: 2020.
szept. 26., Szo, 21:36):

**Comment by pcubillos** [comment]
Hmm, I'm puzzled. Do you have the screen output that you got when you did ``python setup.py install``? Could you please copy and paste?

**Comment by klagyi** [comment]
(base) klagyi@Peters-Air mc3 % python setup.py install

running install

running bdist_egg

running egg_info

writing mc3.egg-info/PKG-INFO

writing dependency_links to mc3.egg-info/dependency_links.txt

writing entry points to mc3.egg-info/entry_points.txt

writing requirements to mc3.egg-info/requires.txt

writing top-level names to mc3.egg-info/top_level.txt

reading manifest file 'mc3.egg-info/SOURCES.txt'

reading manifest template 'MANIFEST.in'

writing manifest file 'mc3.egg-info/SOURCES.txt'

installing library code to build/bdist.macosx-10.9-x86_64/egg

running install_lib

running build_py

running build_ext

creating build/bdist.macosx-10.9-x86_64/egg

creating build/bdist.macosx-10.9-x86_64/egg/mc3

copying build/lib.macosx-10.9-x86_64-3.7/mc3/sampler_driver.py ->
build/bdist.macosx-10.9-x86_64/egg/mc3

copying build/lib.macosx-10.9-x86_64-3.7/mc3/VERSION.py ->
build/bdist.macosx-10.9-x86_64/egg/mc3

copying build/lib.macosx-10.9-x86_64-3.7/mc3/fit_driver.py ->
build/bdist.macosx-10.9-x86_64/egg/mc3

copying build/lib.macosx-10.9-x86_64-3.7/mc3/chain.py ->
build/bdist.macosx-10.9-x86_64/egg/mc3

copying build/lib.macosx-10.9-x86_64-3.7/mc3/__init__.py ->
build/bdist.macosx-10.9-x86_64/egg/mc3

creating build/bdist.macosx-10.9-x86_64/egg/mc3/utils

copying build/lib.macosx-10.9-x86_64-3.7/mc3/utils/log.py ->
build/bdist.macosx-10.9-x86_64/egg/mc3/utils

copying build/lib.macosx-10.9-x86_64-3.7/mc3/utils/__init__.py ->
build/bdist.macosx-10.9-x86_64/egg/mc3/utils

copying build/lib.macosx-10.9-x86_64-3.7/mc3/utils/utils.py ->
build/bdist.macosx-10.9-x86_64/egg/mc3/utils

creating build/bdist.macosx-10.9-x86_64/egg/mc3/rednoise

copying build/lib.macosx-10.9-x86_64-3.7/mc3/rednoise/time_averaging.py ->
build/bdist.macosx-10.9-x86_64/egg/mc3/rednoise

copying build/lib.macosx-10.9-x86_64-3.7/mc3/rednoise/__init__.py ->
build/bdist.macosx-10.9-x86_64/egg/mc3/rednoise

copying build/lib.macosx-10.9-x86_64-3.7/mc3/rednoise/prayer.py ->
build/bdist.macosx-10.9-x86_64/egg/mc3/rednoise

copying build/lib.macosx-10.9-x86_64-3.7/mc3/ns_driver.py ->
build/bdist.macosx-10.9-x86_64/egg/mc3

copying build/lib.macosx-10.9-x86_64-3.7/mc3/mcmc_driver.py ->
build/bdist.macosx-10.9-x86_64/egg/mc3

creating build/bdist.macosx-10.9-x86_64/egg/mc3/lib

copying build/lib.macosx-10.9-x86_64-3.7/mc3/lib/_
binarray.cpython-37m-darwin.so -> build/bdist.macosx-10.9-x86_64/egg/mc3/lib

copying build/lib.macosx-10.9-x86_64-3.7/mc3/lib/_
chisq.cpython-37m-darwin.so -> build/bdist.macosx-10.9-x86_64/egg/mc3/lib

copying build/lib.macosx-10.9-x86_64-3.7/mc3/lib/_dwt.cpython-37m-darwin.so
-> build/bdist.macosx-10.9-x86_64/egg/mc3/lib

copying build/lib.macosx-10.9-x86_64-3.7/mc3/lib/
timeavg.cpython-37m-darwin.so -> build/bdist.macosx-10.9-x86_64/egg/mc3/lib

copying build/lib.macosx-10.9-x86_64-3.7/mc3/__main__.py ->
build/bdist.macosx-10.9-x86_64/egg/mc3

creating build/bdist.macosx-10.9-x86_64/egg/mc3/stats

copying build/lib.macosx-10.9-x86_64-3.7/mc3/stats/time_averaging.py ->
build/bdist.macosx-10.9-x86_64/egg/mc3/stats

copying build/lib.macosx-10.9-x86_64-3.7/mc3/stats/__init__.py ->
build/bdist.macosx-10.9-x86_64/egg/mc3/stats

copying build/lib.macosx-10.9-x86_64-3.7/mc3/stats/stats.py ->
build/bdist.macosx-10.9-x86_64/egg/mc3/stats

copying build/lib.macosx-10.9-x86_64-3.7/mc3/stats/gelman.py ->
build/bdist.macosx-10.9-x86_64/egg/mc3/stats

creating build/bdist.macosx-10.9-x86_64/egg/mc3/plots

copying build/lib.macosx-10.9-x86_64-3.7/mc3/plots/__init__.py ->
build/bdist.macosx-10.9-x86_64/egg/mc3/plots

copying build/lib.macosx-10.9-x86_64-3.7/mc3/plots/plots.py ->
build/bdist.macosx-10.9-x86_64/egg/mc3/plots

byte-compiling build/bdist.macosx-10.9-x86_64/egg/mc3/sampler_driver.py to
sampler_driver.cpython-37.pyc

byte-compiling build/bdist.macosx-10.9-x86_64/egg/mc3/VERSION.py to
VERSION.cpython-37.pyc

byte-compiling build/bdist.macosx-10.9-x86_64/egg/mc3/fit_driver.py to
fit_driver.cpython-37.pyc

byte-compiling build/bdist.macosx-10.9-x86_64/egg/mc3/chain.py to
chain.cpython-37.pyc

byte-compiling build/bdist.macosx-10.9-x86_64/egg/mc3/__init__.py to
__init__.cpython-37.pyc

byte-compiling build/bdist.macosx-10.9-x86_64/egg/mc3/utils/log.py to
log.cpython-37.pyc

byte-compiling build/bdist.macosx-10.9-x86_64/egg/mc3/utils/__init__.py to
__init__.cpython-37.pyc

byte-compiling build/bdist.macosx-10.9-x86_64/egg/mc3/utils/utils.py to
utils.cpython-37.pyc

byte-compiling
build/bdist.macosx-10.9-x86_64/egg/mc3/rednoise/time_averaging.py to
time_averaging.cpython-37.pyc

byte-compiling build/bdist.macosx-10.9-x86_64/egg/mc3/rednoise/__init__.py
to __init__.cpython-37.pyc

byte-compiling build/bdist.macosx-10.9-x86_64/egg/mc3/rednoise/prayer.py to
prayer.cpython-37.pyc

byte-compiling build/bdist.macosx-10.9-x86_64/egg/mc3/ns_driver.py to
ns_driver.cpython-37.pyc

byte-compiling build/bdist.macosx-10.9-x86_64/egg/mc3/mcmc_driver.py to
mcmc_driver.cpython-37.pyc

byte-compiling build/bdist.macosx-10.9-x86_64/egg/mc3/__main__.py to
__main__.cpython-37.pyc

byte-compiling
build/bdist.macosx-10.9-x86_64/egg/mc3/stats/time_averaging.py to
time_averaging.cpython-37.pyc

byte-compiling build/bdist.macosx-10.9-x86_64/egg/mc3/stats/__init__.py to
__init__.cpython-37.pyc

byte-compiling build/bdist.macosx-10.9-x86_64/egg/mc3/stats/stats.py to
stats.cpython-37.pyc

byte-compiling build/bdist.macosx-10.9-x86_64/egg/mc3/stats/gelman.py to
gelman.cpython-37.pyc

byte-compiling build/bdist.macosx-10.9-x86_64/egg/mc3/plots/__init__.py to
__init__.cpython-37.pyc

byte-compiling build/bdist.macosx-10.9-x86_64/egg/mc3/plots/plots.py to
plots.cpython-37.pyc

creating stub loader for mc3/lib/_chisq.cpython-37m-darwin.so

creating stub loader for mc3/lib/_dwt.cpython-37m-darwin.so

creating stub loader for mc3/lib/timeavg.cpython-37m-darwin.so

creating stub loader for mc3/lib/_binarray.cpython-37m-darwin.so

byte-compiling build/bdist.macosx-10.9-x86_64/egg/mc3/lib/_chisq.py to
_chisq.cpython-37.pyc

byte-compiling build/bdist.macosx-10.9-x86_64/egg/mc3/lib/_dwt.py to
_dwt.cpython-37.pyc

byte-compiling build/bdist.macosx-10.9-x86_64/egg/mc3/lib/timeavg.py to
timeavg.cpython-37.pyc

byte-compiling build/bdist.macosx-10.9-x86_64/egg/mc3/lib/_binarray.py to
_binarray.cpython-37.pyc

creating build/bdist.macosx-10.9-x86_64/egg/EGG-INFO

copying mc3.egg-info/PKG-INFO -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO

copying mc3.egg-info/SOURCES.txt ->
build/bdist.macosx-10.9-x86_64/egg/EGG-INFO

copying mc3.egg-info/dependency_links.txt ->
build/bdist.macosx-10.9-x86_64/egg/EGG-INFO

copying mc3.egg-info/entry_points.txt ->
build/bdist.macosx-10.9-x86_64/egg/EGG-INFO

copying mc3.egg-info/requires.txt ->
build/bdist.macosx-10.9-x86_64/egg/EGG-INFO

copying mc3.egg-info/top_level.txt ->
build/bdist.macosx-10.9-x86_64/egg/EGG-INFO

writing build/bdist.macosx-10.9-x86_64/egg/EGG-INFO/native_libs.txt

zip_safe flag not set; analyzing archive contents...

mc3.lib.__pycache__._binarray.cpython-37: module references __file__

mc3.lib.__pycache__._chisq.cpython-37: module references __file__

mc3.lib.__pycache__._dwt.cpython-37: module references __file__

mc3.lib.__pycache__.timeavg.cpython-37: module references __file__

mc3.utils.__pycache__.utils.cpython-37: module references __file__

creating 'dist/mc3-3.0.2-py3.7-macosx-10.9-x86_64.egg' and adding
'build/bdist.macosx-10.9-x86_64/egg' to it

removing 'build/bdist.macosx-10.9-x86_64/egg' (and everything under it)

Processing mc3-3.0.2-py3.7-macosx-10.9-x86_64.egg

removing
'/Users/klagyi/opt/anaconda3/lib/python3.7/site-packages/mc3-3.0.2-py3.7-macosx-10.9-x86_64.egg'
(and everything under it)

creating
/Users/klagyi/opt/anaconda3/lib/python3.7/site-packages/mc3-3.0.2-py3.7-macosx-10.9-x86_64.egg

Extracting mc3-3.0.2-py3.7-macosx-10.9-x86_64.egg to
/Users/klagyi/opt/anaconda3/lib/python3.7/site-packages

mc3 3.0.2 is already the active version in easy-install.pth

Installing mc3 script to /Users/klagyi/opt/anaconda3/bin


Installed
/Users/klagyi/opt/anaconda3/lib/python3.7/site-packages/mc3-3.0.2-py3.7-macosx-10.9-x86_64.egg

Processing dependencies for mc3==3.0.2

Searching for matplotlib==3.2.1

Best match: matplotlib 3.2.1

Adding matplotlib 3.2.1 to easy-install.pth file


Using /Users/klagyi/opt/anaconda3/lib/python3.7/site-packages

Searching for scipy==1.4.1

Best match: scipy 1.4.1

Adding scipy 1.4.1 to easy-install.pth file


Using /Users/klagyi/opt/anaconda3/lib/python3.7/site-packages

Searching for numpy==1.18.4

Best match: numpy 1.18.4

Adding numpy 1.18.4 to easy-install.pth file

Installing f2py script to /Users/klagyi/opt/anaconda3/bin

Installing f2py3 script to /Users/klagyi/opt/anaconda3/bin

Installing f2py3.7 script to /Users/klagyi/opt/anaconda3/bin


Using /Users/klagyi/opt/anaconda3/lib/python3.7/site-packages

Searching for python-dateutil==2.8.1

Best match: python-dateutil 2.8.1

Adding python-dateutil 2.8.1 to easy-install.pth file


Using /Users/klagyi/opt/anaconda3/lib/python3.7/site-packages

Searching for pyparsing==2.4.7

Best match: pyparsing 2.4.7

Adding pyparsing 2.4.7 to easy-install.pth file


Using /Users/klagyi/opt/anaconda3/lib/python3.7/site-packages

Searching for kiwisolver==1.2.0

Best match: kiwisolver 1.2.0

Adding kiwisolver 1.2.0 to easy-install.pth file


Using /Users/klagyi/opt/anaconda3/lib/python3.7/site-packages

Searching for cycler==0.10.0

Best match: cycler 0.10.0

Adding cycler 0.10.0 to easy-install.pth file


Using /Users/klagyi/opt/anaconda3/lib/python3.7/site-packages

Searching for six==1.14.0

Best match: six 1.14.0

Adding six 1.14.0 to easy-install.pth file


Using /Users/klagyi/opt/anaconda3/lib/python3.7/site-packages

Finished processing dependencies for mc3==3.0.2

(base) klagyi@Peters-Air mc3 %


Patricio Cubillos <notifications@github.com> ezt írta (időpont: 2020.
szept. 26., Szo, 22:15):

**Comment by pcubillos** [comment]
OK, I think I got it.  When you try to run/import mc3, do you do it from this folder ``/Users/klagyi/astro/pythoncodes/mc3/``?
The problem is that in that case the import is looking at the code in your local folder (``/Users/klagyi/astro/pythoncodes/mc3/mc3``).  However, when you install the package, the code with the compiled binaries are placed in this folder: ``/Users/klagyi/opt/anaconda3/lib/python3.7/site-packages/mc3-3.0.2-py3.7-macosx-10.9-x86_64.egg`` (which makes the code visible from any folder that you are in).

So, I'm guessing that if you try to import mc3 from any folder other than ``/Users/klagyi/astro/pythoncodes/mc3/`` it should work just fine.

Can you try that? and if it still fails, can you tell me whether it shows the same paths in the Traceback error log as in your original post.

**Comment by klagyi** [comment]
You got it ;) Now it works. Or at least I don't get any error when I import
mc3.

Thanks a lot Patricio!

Regards,
Peter

Patricio Cubillos <notifications@github.com> ezt írta (időpont: 2020.
szept. 27., V, 10:01):

**Comment by pcubillos** [comment]
Great! That was a tricky one!
Good luck on your research!
Best,
p

**Comment by klagyi** [comment]
Hi Patricio,

It's me again :) On my computer mc3 works fine.

We tried to install it on another computer (Windows). The installation
starts, but it stops due to an error of the Microsoft Visual Studios C++
(see attached screenshot). We installed visual studios without any error,
but mc3 installation still doesn't work. Do you have any idea what is the
problem? We didn't find Visual Studios 14.0, we installed the latest
version (16.0) instead.

Regards,
Peter

Patricio Cubillos <notifications@github.com> ezt írta (időpont: 2020.
szept. 27., V, 10:22):

**Comment by pcubillos** [comment]
Hi Peter,
I don't see the screenshot, can you try to add it up into the issue directly through github or else sent it by email (patrcio.cubillos[at]oeaw.ac.at).   I can promise much since I haven't own a windows machine in a long time and haven't tested the code for it.

Thanks,
p
