### ISSUE TITLE
**kwarg/dict support for indparams

### ISSUE THREAD

**Issue by whtowbin** [pcubillos/mc3#136]
It would be very helpful to have indparams accept a dictionary so we can easily change input values in a function without inputting every possible argument in an ordered list. 
something like indparams = {'x':x, 'a':False, 'Temp':100}

**Comment by pcubillos** [comment]
Hi @whtowbin 
I think this is a good idea and (probably) not too complicated to implement, I'll see what I can do. Thanks for the suggestion.

**Comment by whtowbin** [comment]
@pcubillos,I am happy to help out with this if you direct me to the proper files.
