### ISSUE TITLE
Cannot build mc3

### ISSUE THREAD

**Issue by fenwickdh** [pcubillos/mc3#139]
I'm a newbie to mc3.  When I try to install it, I get 

--------------------
.....
  creating build\temp.win-amd64-3.8
  creating build\temp.win-amd64-3.8\Release
  creating build\temp.win-amd64-3.8\Release\src_c
  "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.30.30705\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\...\AppData\Local\Temp\pip-build-env-pzxyxxq1\overlay\Lib\site-packages\numpy\core\include -Isrc_c/include/ -Ic:\users\...\python38\include -Ic:\users\fenwick\appdata\local\programs\python\python38\Include -IC:\Users\...\AppData\Local\Temp\pip-build-env-pzxyxxq1\overlay\Lib\site-packages\numpy\core\include -Isrc_c/include/ -Ic:\users\...\appdata\local\programs\python\python38\include -Ic:\users\...\appdata\local\programs\python\python38\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.30.30705\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.30.30705\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" /Tcsrc_c/_binarray.c /Fobuild\temp.win-amd64-3.8\Release\src_c/_binarray.obj -ffast-math
  cl : Command line warning D9002 : ignoring unknown option '-ffast-math'
  _binarray.c
  src_c/include/stats.h(98): error C2036: 'void *': unknown size
  src_c/include/stats.h(99): error C2036: 'void *': unknown size
  src_c/include/stats.h(102): error C2036: 'void *': unknown size
  src_c/include/stats.h(103): error C2036: 'void *': unknown size
  src_c/include/stats.h(105): error C2036: 'void *': unknown size
  src_c/_binarray.c(57): error C2036: 'void *': unknown size
  src_c/_binarray.c(59): error C2036: 'void *': unknown size
  src_c/_binarray.c(60): error C2036: 'void *': unknown size
  src_c/_binarray.c(70): error C2036: 'void *': unknown size
  src_c/_binarray.c(71): error C2036: 'void *': unknown size
  src_c/_binarray.c(73): error C2036: 'void *': unknown size
  src_c/_binarray.c(74): error C2036: 'void *': unknown size
  src_c/_binarray.c(76): error C2036: 'void *': unknown size
  src_c/_binarray.c(77): error C2036: 'void *': unknown size
  error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.30.30705\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  ----------------------------------------
  ERROR: Failed building wheel for mc3
Failed to build mc3
ERROR: Could not build wheels for mc3, which is required to install pyproject.toml-based projects
-----------------------------------------------

Any thoughts on how I can resolve this?  

Thanks!

**Comment by pcubillos** [comment]
Hi @fenwickdh 
I see the problem, this is trying to compile on a Windows machine.  Unfortunately, I have only capability to test on Linux or OSX machines, as I have no experience packaging python projects for Windows. Sorry.
