### ISSUE TITLE
bad syntax in "resume mode"

### ISSUE THREAD

**Issue by frandrieu** [pcubillos/mc3#142]
Hello,

I got the error 

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mc3/utils/log.py", line 45, in __init__
    self.file = open(self.logname, "aw")

ValueError: must have exactly one of create/read/write/append mode

while trying to resume a previous run. Solved it just by replacing 
              self.file = open(self.logname, "aw")
with
              self.file = open(self.logname, "a")
line 45 in log.py 

I thought you might be interested. Thank you for this great mcmc package btw

François

**Comment by pcubillos** [comment]
Hi Francois, Thanks! This was fixed the most recent version (3.0.12)
