### ISSUE TITLE
mc3 3.1.4 not working on debian 12 / fedora 40 

### ISSUE THREAD

**Issue by tfenouillet** [pcubillos/mc3#154]
Hi
I'm trying to install mc3 on a laptop for testing:
I already tried on debian 12 / fedora 40 /almalinux 8 and 9 
on almalinux no problem ( with python 3.9 and 3.11) 
on debian or fedora ( same error ):
```
python -m venv test-mc3 
cd test-mc3
source ./bin/activate
pip install mc3
python
>>>import mc3
```
result in :
```
  File "<stdin>", line 1, in <module>
  File "./test-mc3/lib64/python3.12/site-packages/mc3/__init__.py", line 4, in <module>
    from .sampler_driver import *
  File "./test-mc3/lib64/python3.12/site-packages/mc3/sampler_driver.py", line 17, in <module>
    from .fit_driver import fit
  File "./test-mc3/lib64/python3.12/site-packages/mc3/fit_driver.py", line 11, in <module>
    from . import stats as ms
  File "./test-mc3/lib64/python3.12/site-packages/mc3/stats/__init__.py", line 5, in <module>
    from .stats import *
  File "./test-mc3/lib64/python3.12/site-packages/mc3/stats/stats.py", line 31, in <module>
    import _binarray as ba
ImportError: ./test-mc3/lib/python3.12/site-packages/mc3/lib/_binarray.cpython-312-x86_64-linux-gnu.so: undefined symbol: _ZGVbN2v_exp
```
everything else seems to work
thanks for your work
T.

**Comment by pcubillos** [comment]
Hi, could you check if this version solves the issue, please:

```shell
# Instead of pip install mc3, clone branch and install locally
git clone -b c_compiler https://github.com/pcubillos/mc3
cd mc3
pip install -e .
```
Thanks!

**Comment by tfenouillet** [comment]
Thanks a lot its working
cheers

**Comment by pcubillos** [comment]
Awesome!
Another user had told me about this issue a few days ago.  It's an obscure C-compilation bug for some specific combination of OS  and compiler (some typically default libraries were in fact not being included at compilation time).   So, I had a potential solution baked, but no real test of it (until now).

I'll push the bug-fix into the main branch in the next couple of days.
Cheers.
